app = "fly-db-ipieug"
primary_region = "lax"

[env]
    PORT = "3000"

[http_service]
    internal_port = 3000
    auto_start_machines = true
    auto_stop_machines = true
    force_https = true
    min_machines_running = 0
    processes = [ "app" ]

[[vm]]
    cpu_kind = "shared"
    cpus = 1
    memory = "1gb"
    memory_mb = 1_024
